/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PmtCard {
    }
    interface PmtFooter {
    }
    interface PmtTimer {
        "cardNumber": string;
        "cvv": string;
        "expDate": string;
    }
}
declare global {
    interface HTMLPmtCardElement extends Components.PmtCard, HTMLStencilElement {
    }
    var HTMLPmtCardElement: {
        prototype: HTMLPmtCardElement;
        new (): HTMLPmtCardElement;
    };
    interface HTMLPmtFooterElement extends Components.PmtFooter, HTMLStencilElement {
    }
    var HTMLPmtFooterElement: {
        prototype: HTMLPmtFooterElement;
        new (): HTMLPmtFooterElement;
    };
    interface HTMLPmtTimerElement extends Components.PmtTimer, HTMLStencilElement {
    }
    var HTMLPmtTimerElement: {
        prototype: HTMLPmtTimerElement;
        new (): HTMLPmtTimerElement;
    };
    interface HTMLElementTagNameMap {
        "pmt-card": HTMLPmtCardElement;
        "pmt-footer": HTMLPmtFooterElement;
        "pmt-timer": HTMLPmtTimerElement;
    }
}
declare namespace LocalJSX {
    interface PmtCard {
    }
    interface PmtFooter {
    }
    interface PmtTimer {
        "cardNumber"?: string;
        "cvv"?: string;
        "expDate"?: string;
    }
    interface IntrinsicElements {
        "pmt-card": PmtCard;
        "pmt-footer": PmtFooter;
        "pmt-timer": PmtTimer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pmt-card": LocalJSX.PmtCard & JSXBase.HTMLAttributes<HTMLPmtCardElement>;
            "pmt-footer": LocalJSX.PmtFooter & JSXBase.HTMLAttributes<HTMLPmtFooterElement>;
            "pmt-timer": LocalJSX.PmtTimer & JSXBase.HTMLAttributes<HTMLPmtTimerElement>;
        }
    }
}
